version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/react"
    versions:
    - 6.3.0
    - 6.3.1
  - dependency-name: "@sentry/tracing"
    versions:
    - 6.3.0
    - 6.3.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.4.0
  - dependency-name: "@iconify/icons-simple-icons"
    versions:
    - 1.1.14
    - 1.1.15
    - 1.1.16
    - 1.1.17
    - 1.1.18
    - 1.1.19
    - 1.1.20
  - dependency-name: react-spring
    versions:
    - 9.0.0
    - 9.1.0
    - 9.1.1
  - dependency-name: styled-components
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: "@bamdadsabbagh/stylelint-config"
    versions:
    - 1.2.183
    - 1.2.186
    - 1.2.188
    - 1.3.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: "@bamdadsabbagh/eslint-config"
    versions:
    - 1.5.17
    - 1.7.0
    - 1.8.0
    - 1.8.3
    - 1.9.1
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
    - 5.1.9
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: "@iconify/icons-logos"
    versions:
    - 1.1.7
    - 1.1.9
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: react-scripts
    versions:
    - 4.0.2
    - 4.0.3
  - dependency-name: typescript
    versions:
    - 4.2.2
