stages:
  - build
  - base_image_update

include:
  - template: Jobs/Build.gitlab-ci.yml

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE != "schedule"'
      when: always

base_image_update:on-schedule:
  stage: base_image_update
  only:
    - schedules
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "base_image_update..."
    - apk update
    - apk add git bash jq curl
    - git clone https://github.com/bamdadsabbagh/gitlab-docker-base-image-update
    - cd gitlab-docker-base-image-update
    - chmod +x run.sh
    - ./run.sh
