stages:
  - build
  - base_image_update

include:
  - remote: https://gitlab.com/bamdadsabbagh/gitlab-ci-templates/raw/master/templates/build_docker.gitlab-ci.yml

build:
  stage: build
  extends: .build_docker

base_image_update:on-schedule:
  stage: base_image_update
  only:
    - schedules
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "base_image_update..."
    - apk update
    - apk add git bash jq curl
    - git clone https://github.com/bamdadsabbagh/gitlab-docker-base-image-update
    - cd gitlab-docker-base-image-update
    - chmod +x run.sh
    - ./run.sh
