---
name: codeclimate
on:
  push:
    branches: [master]
jobs:
  codeclimate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm -g i pnpm
      - run: pnpm i --frozen-lockfile --ignore-scripts
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
        with:
          coverageCommand: pnpm coverage
          debug: true
