name: hourly-base-image-check

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - run: echo ::set-env name=BASE_IMAGE::$(cat Dockerfile | awk '{ if ($1=="FROM") print $2 }' | tail -n 1)
        shell: bash

      - run: docker login -u ${{ github.repository_owner }} -p ${{ github.token }} docker.pkg.github.com

      - run: |
          if ./check.sh node:alpine docker.pkg.github.com/bamdadsabbagh/bamdadsabbagh-www/bamdadsabbagh-www:latest; then
            echo ::set-env name=IS_UP_TO_DATE::true
          else
            echo ::set-env name=IS_UP_TO_DATE::false
          fi
      
      - if: env.IS_UP_TO_DATE == true
        run: echo "hello there"