name: hourly-base-image-check

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - run: echo ::set-env name=BASE_IMAGE::$(cat Dockerfile | awk '{ if ($1=="FROM") print $2 }' | tail -n 1)
        shell: bash

      - run: docker login -u ${{ github.repository_owner }} -p ${{ github.token }} docker.pkg.github.com

      - run: |
          docker pull ${{ env.BASE_IMAGE }} \
          && docker pull docker.pkg.github.com/bamdadsabbagh/bamdadsabbagh-www/bamdadsabbagh-www:latest
      
      - run: |
          IMAGE_LAYERS=`docker inspect nginx:alpine | jq -r .[].RootFS.Layers` \
          && BASE_IMAGE_LAYERS=`docker inspect docker.pkg.github.com/bamdadsabbagh/bamdadsabbagh-www/bamdadsabbagh-www:latest | jq -r .[].RootFS.Layers` \
          && BASE_IMAGE_LAYERS_LENGTH=`docker inspect docker.pkg.github.com/bamdadsabbagh/bamdadsabbagh-www/bamdadsabbagh-www:latest | jq -r '.[].RootFS.Layers | length'``

      - run: |
          echo IMAGE_LAYERS

