name: hourly-base-image-check

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - run: echo ::set-env name=BASE_IMAGE::$(cat Dockerfile | awk '{ if ($1=="FROM") print $2 }' | tail -n 1)
        shell: bash

      - run: |
          ls -al \
          && echo ${{ env.BASE_IMAGE }}